[versions]
android-gradle = "8.8.0"
colorslider = "2.0.7"
constraintlayout = "2.2.0"
espresso = "3.6.1"
junit = "4.13.2"
junit-androidx = "1.2.1"
kotlin = "2.1.0"
material = "1.12.0"
maven-publish = "0.30.0"
recyclerview = "1.4.0"
viewpager2 = "1.1.0"

[libraries]
colorslider = { module = "com.github.naz013:ColorSlider", version.ref = "colorslider" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-androidx = { module = "androidx.test.ext:junit", version.ref = "junit-androidx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }